- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: PassengerGear
  equipment:
    outerClothing: ClothingOuterWinterCoatToggleable
    belt: ClothingBeltUtility
    back: ClothingBackpackSatchelSalvage
    shoes: ClothingShoesBootsWinter
    jumpsuit: ClothingUniformJumpsuitOperative
    gloves: ClothingHandsGlovesColorBlack
    mask: ClothingMaskGasExplorer

